name: Publish to Xanadu

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build publish
      env:
        VERSION: ${{ github.event.tag_name }}
        USERNAME: ${{ secrets.MAVEN_USERNAME }}
        TOKEN: ${{ secrets.MAVEN_PASSWORD }}
        
